### ISSUE TITLE
OS_CACERT environment variable is not honored

### ISSUE THREAD

**Issue by facundofc** [dosaboy/openstack-toolkit#4]
`curl` calls on `lib/openstack_client` fail on an environment where a CA has been set up. These calls are failing with:

```
$ curl -H 'X-Auth-Token: ...' https://keystone.public.ossite1.nextiva.openstack:35357/v3/endpoints
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

causing nearly all functions on that file to fail and overall the script to spit a quite enigmatic message:

```
$ openstack-toolkit.octavia --create-lb-monitor-map 9224b971-3cfe-415e-826f-294ba79021c2
INFO: fetching token
INFO: pre-fetching information...[ports][loadbalancers]
ERROR: 
Done.
```

**Comment by dosaboy** [comment]
I should have mentioned that if your cert is in /etc/ssl/certs/ca-certificates.crt it should be accessible by the snap so this really only applies to cases where it is not in /etc/ssl/certs/ca-certificates.crt
